import { Campaign, Discussion, Event, User, Resource } from '../types';

export const MOCK_USER: User = {
  id: 'u1',
  username: 'eco_warrior',
  fullName: 'Wangari Doe',
  avatarUrl: 'https://picsum.photos/200',
  impactPoints: 1250,
  badges: ['Early Adopter', 'Tree Hugger', 'Event Organizer'],
  role: 'user',
};

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    title: 'Reforest the Rift Valley',
    description: 'Join us in planting 10,000 indigenous trees to restore the water catchment areas.',
    targetTrees: 10000,
    plantedTrees: 4500,
    imageUrl: 'https://picsum.photos/600/400?random=1',
    organizer: 'Green Belt Movement',
    organizerId: 'u1',
    organizerAvatar: 'https://picsum.photos/200',
    location: 'Nakuru, Kenya',
    tags: ['Restoration', 'Water', 'Community'],
    daysLeft: 15,
    isPublic: true,
    status: 'active',
    participants: [],
    pendingParticipants: [],
    updates: [],
    completionPhotos: [],
    isCompletionPending: false,
    createdAt: new Date().toISOString(),
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c2',
    title: 'Urban Canopy Project',
    description: 'Creating green corridors in the city center to reduce heat islands.',
    targetTrees: 500,
    plantedTrees: 120,
    imageUrl: 'https://picsum.photos/600/400?random=2',
    organizer: 'City Green',
    organizerId: 'u1',
    organizerAvatar: 'https://picsum.photos/200',
    location: 'Nairobi, Kenya',
    tags: ['Urban', 'Shade'],
    daysLeft: 30,
    isPublic: true,
    status: 'active',
    participants: [],
    pendingParticipants: [],
    updates: [],
    completionPhotos: [],
    isCompletionPending: false,
    createdAt: new Date().toISOString(),
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c3',
    title: 'School Fruit Forest',
    description: 'Planting fruit trees in 5 local primary schools for nutrition and education.',
    targetTrees: 200,
    plantedTrees: 200,
    imageUrl: 'https://picsum.photos/600/400?random=3',
    organizer: 'EdTech Eco',
    organizerId: 'u1',
    organizerAvatar: 'https://picsum.photos/200',
    location: 'Mombasa, Kenya',
    tags: ['Education', 'Food Security'],
    daysLeft: 0,
    isPublic: true,
    status: 'completed',
    participants: [],
    pendingParticipants: [],
    updates: [],
    completionPhotos: [],
    isCompletionPending: false,
    createdAt: new Date().toISOString(),
    startDate: new Date().toISOString(),
    endDate: new Date().toISOString(),
  },
];

export const MOCK_DISCUSSIONS: Discussion[] = [
  {
    id: 'd1',
    title: 'Best indigenous trees for dry areas?',
    content: 'I am looking to start a project in a semi-arid area. Any recommendations on species that require minimal water after establishment?',
    author: MOCK_USER,
    upvotes: 45,
    commentsCount: 12,
    postedAt: '2 hours ago',
    category: 'Help',
  },
  {
    id: 'd2',
    title: 'We just hit 50% of our goal!',
    content: 'Thanks to everyone who donated seedlings this weekend. The Rift Valley project is moving fast.',
    author: { ...MOCK_USER, username: 'project_lead', fullName: 'John Smith' },
    upvotes: 128,
    commentsCount: 34,
    postedAt: '5 hours ago',
    category: 'Success Story',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Karura Forest Clean-up',
    description: 'Join us for a community clean-up event at Karura Forest.',
    date: '2024-08-24',
    time: '09:00',
    location: 'Gate C, Karura',
    attendees: ['u1'],
    type: 'In-Person',
    imageUrl: 'https://picsum.photos/200/200?random=10',
    organizerId: 'u1',
    organizerName: 'Wangari Doe',
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'e2',
    title: 'Agroforestry Webinar',
    description: 'Learn about sustainable agroforestry practices.',
    date: '2024-08-27',
    time: '18:00',
    location: 'Zoom',
    attendees: ['u1'],
    type: 'Online',
    imageUrl: 'https://picsum.photos/200/200?random=11',
    organizerId: 'u1',
    organizerName: 'Wangari Doe',
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_RESOURCES: Resource[] = [
  { id: 'r1', title: 'Tree Planting Guide 101', type: 'PDF', category: 'Guides', url: '#' },
  { id: 'r2', title: 'Soil Health Analysis', type: 'Video', category: 'Science', url: '#' },
  { id: 'r3', title: 'Community Organizing Handbook', type: 'Article', category: 'Community', url: '#' },
];
